
# Check for local settings
try %{ source .kakrc.local }

colorscheme monokai

# Load plugin manager
source "%val{config}/plugins/plug.kak/rc/plug.kak"
source "%val{config}/kakrc.tmux"
# source "./kakrc.i3"

# Plugins
eval %sh{kak-lsp --kakoune -s $kak_session}
lsp-enable

# Plugins
plug "andreyorst/fzf.kak" %{
    map global normal <c-p> ': fzf-mode<ret>'
}

plug "andreyorst/powerline.kak" defer "powerline" %{
    set-option global powerline_format 'git client session bufname filetype mode_info line_column position'
} defer  powerline_gruvbox %{
    powerline-theme gruvbox
} config %{
    powerline-start
}

plug "ul/kak-lsp" do %{
    cargo build --release --locked
    cargo install --force --path .
} config %{
    set-option global lsp_completion_trigger "execute-keys 'h<a-h><a-k>\S[^\h\n,=;*(){}\[\]]\z<ret>'"
    set-option global lsp_diagnostic_line_error_sign "!"
    set-option global lsp_diagnostic_line_warning_sign "?"

    hook global WinSetOption filetype=(rust) %{
        lsp-enable-window
        lsp-auto-hover-enable
        lsp-auto-hover-insert-mode-disable
        set-option window lsp_hover_anchor true
        set-face window DiagnosticError default+u
        set-face window DiagnosticWarning default+u
    }

    hook global WinSetOption filetype=rust %{
        set-option window lsp_server_configuration rust.clippy_preference="on"
    }

    hook global KakEnd .* lsp-exit
}

set-face global InsertCursor default,green+B

hook global ModeChange .*:.*:insert %{
    set-face window PrimaryCursor InsertCursor
    set-face window PrimaryCursorEol InsertCursor
}

hook global ModeChange .*:insert:.* %{ try %{
    unset-face window PrimaryCursor
    unset-face window PrimaryCursorEol
} }

eval %sh{ git rev-parse --is-inside-work-tree 2>/dev/null 1>/dev/null && printf %s "
    hook global BufWritePost .* %{ git show-diff }
    hook global BufReload .* %{ git show-diff }
"}

hook global RegisterModified '"' %{ %sh{
    if [ -n "$DISPLAY" ]; then
        printf %s "$kak_main_reg_dquote" | xsel --input --clipboard
    elif [ -n "$TMUX"]; then
        tmux set-buffer -- "$kak_main_reg_dquote"
    fi
}}

define-command build %{
    evaluate-commands -try-client build_output make
}

# Tab stuff
set-option global tabstop 4
set-option global indentwidth 4


# No tabs... just spaces
map global insert <tab> "    "

# Shift tab unindents
map global insert <s-tab> '<a-;><lt>'

# Auto reload open files
set-option global autoreload true

# Turn off clippy
set-option global ui_options ncurses_assistant=none
set-option global ui_options terminal_assistant=none

# OS Clipboard interaction
map global user y -docstring 'Copy to clipboard' '<a-|>!xsel -bi<ret>'
map global user d -docstring 'Cut to clipboard' '!xsel -bi<ret>'

# Map user-q to close current buffer
map global user q -docstring 'Close current buffer' ':delete-buffer<ret>'

# Map user-m to make
map global user m -docstring 'Make' ':build<ret>'

# map user-a to select all occurences of main selection
map global user a -docstring 'Select all occurences of main selection' '*%s<ret>'

# map user-w to set line wrapping
map global user w -docstring 'Set line wrapping for current buffer' ':addhl buffer/ wrap<ret>'

# map user-f to run code formatting
map global user f -docstring 'Run code formatting' ':format<ret>'

map global user n -docstring 'Goto next function' ':lsp-next-function<ret>'
map global user p -docstring 'Goto previous function' ':lsp-previous-function<ret>'
map global user h -docstring 'Toggle header/source' ':clangd-switch-source-header<ret>'

# map user-e to find next error
map global user e -docstring 'Find next error' ':lsp-find-error<ret>'

map global user c -docstring 'Git checkout current file' ':git checkout %val{buffile}<ret>'

# Comments
map global normal '#' -docstring 'Comment line' :comment-line<ret>
map global normal '<a-#>' -docstring 'Comment block' :comment-block<ret>

# Hooks for C/C++ family of files
hook global WinSetOption filetype=(c|cpp|objc) %{

    require-module c-family

    lsp-enable-window
    lsp-auto-hover-enable

    # Set clang-format for formatting
    set-option window formatcmd 'clang-format'

    # Format the code on exiting insert and saving buffer
    hook buffer BufWritePre .* %{ format }
}

# Hooks for python files
hook global WinSetOption filetype=python %{

    lsp-enable-window
    lsp-auto-hover-enable

    # Set format command to autopep8
    set-option window formatcmd "autopep8 -"

    # Install hook to format on save
    hook buffer BufWritePre .* %{ format }
}

# Hooks for cmake files
hook global WinSetOption filetype=cmake %{

    # Set format command to cmake-format
    set window formatcmd "cmake-format -"

    # Install hook to format on save
    hook buffer BufWritePre .* %{ format }
}

# Hooks for Rust files
hook global WinSetOption filetype=rust %{

    # Set format command to rustfmt
    set window formatcmd "rustfmt"

    # Install hook to format on save
    hook buffer BufWritePre .* %{ format }
}

# Remove trailing whitespace on buffer write
hook global BufWritePre .* %{ try %{ execute-keys -draft \%s\h+$<ret>d } }

# Show line numbers
add-highlighter global/ number-lines -hlcursor

# Still don't know what this does
add-highlighter global/ show-matching

# Highlight the current line
add-highlighter global/ line '%val{cursor_line}' default,black


# map user-<ret> to spawn a new kakoune client
map global user <ret> -docstring 'Open a new kak client' ':new<ret>'
